POST http://localhost:3000/api/cronograma
Content-Type: application/json

{
    "inscricao": "Fulano",
    "avaliacao": "111.111.000-00",
    "resultado": "email@email.com"
}

###

GET http://localhost:3000/api/autor


###
GET http://localhost:3000/api/autor/641af21e1f27d1bd5abc65ce

###
GET http://localhost:3000/api/autor/641af21e1f27d1bd5abc65cd


###
DELETE http://localhost:3000/api/autor/641af21e1f27d1bd5abc65ce

###
DELETE http://localhost:3000/api/autor/641af21e1f27d1bd5abc65cb


###
PUT http://localhost:3000/api/autor/641b95e4177df53ac0f985af
Content-Type: application/json

{
    "nome": "FULANO JÚNIOR",
    "cpf": "111.111.111-00",
    "email": "email@email.com",
    "telefone": "(00) 00000-0000",
    "endereco": "100 Sul, lt 10, 00000-000 Palmas - TO, BR",
    "formacao": "alguma"
}